# PySpark Dataframes and Spark Dataframes

In this example, you will practice a few basics with dataframes using PySpark (Spark, distributed), and Pandas (single machine in memory). The data scientists at Red Ventures use Databricks/Spark extensively, so we want to give you this introduction. However, most of the rest of this program will be taught with Pandas.

By the end of the activity you should be able to:

* Read in a file from the Databricks filestore
* Do basic dataframe manipulations with Spark
* Perform the same dataframe manipulations with Pandas.

In [2]:
# Importing pandas so we have access to dataframe API
import pandas as pd

## The Databricks file system

Just like your laptop has a file system where you can store data and retrieve it, so does Databricks. Run the command below to see some of the many example datasets that Databricks has made available.

In [5]:
# "dbutils.fs.ls" is much like typing "ls" from the terminal or Git Bash. It returns a list of the files in that directory.
# "display" lets you see the results since "dbutils.fs.ls" is returned as a dataframe.

display(dbutils.fs.ls("/databricks-datasets/Rdatasets/data-001/csv/datasets/"))

## Read in the file

As you can see above, there are many different datasets available in this directory alone. Feel free to explore with the other datasets at the bottom of this notebook. The shortcuts to add new cells are "esc+a" (above) or "esc+b" (below).

Now, read the file as a new PySpark Dataframe by executing the command below.

In [7]:
df = sqlContext.read.csv("dbfs:/databricks-datasets/Rdatasets/data-001/csv/datasets/mtcars.csv", header="true", inferSchema = "true")

### 1) Display the Dataframe in the next cell.

Remember, Spark is lazily executed. You have not actually read the dataframe until you perform an action that requires it. Simply returning "df" will only show you the type of data structure that "df" is.

In [9]:
## TODO
display(df)

### 2) Filter the dataframe so it only shows rows with MPG greater than 20 and display it.

In [11]:
#val diamonds = sqlContext.read.format("csv")
import pandas as pd
df = sqlContext.read.csv("dbfs:/databricks-datasets/Rdatasets/data-001/csv/datasets/mtcars.csv", header="true", inferSchema = "true")
#pandas_df = pd.read_csv("dbfs:/databricks-datasets/Rdatasets/data-001/csv/datasets/mtcars.csv", header='infer')
#print(df['desc'])
# percentile list 
perc =[.20, .40, .60, .80] 
  
# list of dtypes to include 
include =['object', 'float', 'int'] 
  
# calling describe method 
#desc = df.describe(percentiles = perc, include = include) 
display(df)
#df.filter('mpg>20').filter('cyl=4').count()

_c0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.9,2.62,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.9,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.32,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.44,17.02,0,0,3,2
Valiant,18.1,6,225.0,105,2.76,3.46,20.22,1,0,3,1
Duster 360,14.3,8,360.0,245,3.21,3.57,15.84,0,0,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.19,20.0,1,0,4,2
Merc 230,22.8,4,140.8,95,3.92,3.15,22.9,1,0,4,2
Merc 280,19.2,6,167.6,123,3.92,3.44,18.3,1,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.44,18.9,1,0,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.07,17.4,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.73,17.6,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.78,18.0,0,0,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.25,17.98,0,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.0,5.424,17.82,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Fiat 128,32.4,4,78.7,66,4.08,2.2,19.47,1,1,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.9,1,1,4,1
Toyota Corona,21.5,4,120.1,97,3.7,2.465,20.01,1,0,3,1
Dodge Challenger,15.5,8,318.0,150,2.76,3.52,16.87,0,0,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.3,0,0,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.84,15.41,0,0,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.9,1,1,4,1
Porsche 914-2,26.0,4,120.3,91,4.43,2.14,16.7,0,1,5,2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.17,14.5,0,1,5,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.77,15.5,0,1,5,6
Maserati Bora,15.0,8,301.0,335,3.54,3.57,14.6,0,1,5,8
Volvo 142E,21.4,4,121.0,109,4.11,2.78,18.6,1,1,4,2

In [12]:
## TODO
import pandas as pd
df = sqlContext.read.csv("dbfs:/databricks-datasets/Rdatasets/data-001/csv/datasets/mtcars.csv", header="true", inferSchema = "true")
#Blast = pd.read_csv('SPECIES_BLAST_DATA.CSV')
.option("header", "true")

In [13]:
import pandas as pd
df = sqlContext.read.format("dbfs:/databricks-datasets/Rdatasets/data-001/csv/datasets/mtcars.csv", header="true", inferSchema = "true")
  .option("header", "true")
  .option("inferSchema", "true")
  .load("dbfs:/databricks-datasets/Rdatasets/data-001/csv/datasets/mtcars.csv", header="true", inferSchema = "true")

### 3) Use PySpark to count how many rows have MPG greater than 20.

In [15]:
# TODO#val diamonds = sqlContext.read.format("csv")
import pandas as pd
df = sqlContext.read.csv("dbfs:/databricks-datasets/Rdatasets/data-001/csv/datasets/mtcars.csv", header="true", inferSchema = "true")
#pandas_df = pd.read_csv("dbfs:/databricks-datasets/Rdatasets/data-001/csv/datasets/mtcars.csv", header='infer')
#print(df['desc'])
# percentile list 
perc =[.20, .40, .60, .80] 
  
# list of dtypes to include 
include =['object', 'float', 'int'] 
  
# calling describe method 
#desc = df.describe(percentiles = perc, include = include) 
#display(df)
df.filter('mpg>20').filter('cyl=4').count()

### 4) What is the average MPG for the 4 cylinder, 6 cylinder, and 8 cylinder cars?

In [17]:

import pandas as pd
df = sqlContext.read.csv("dbfs:/databricks-datasets/Rdatasets/data-001/csv/datasets/mtcars.csv", header="true", inferSchema = "true")
#pandas_df = pd.read_csv("dbfs:/databricks-datasets/Rdatasets/data-001/csv/datasets/mtcars.csv", header='infer')
#print(df['desc'])
# percentile list 
perc =[.20, .40, .60, .80] 
  
# list of dtypes to include 
include =['object', 'float', 'int'] 
  
# calling describe method 
#desc = df.describe(percentiles = perc, include = include) 
#display(df)
#df.filter('mpg>20').filter('cyl=4').count()
display(df.groupBy('cyl').avg('mpg'))

cyl,avg(mpg)
6,19.74285714285714
4,26.663636363636364
8,15.100000000000003

## Converting from PySpark to Pandas

Use the code in the next cell to convert your dataframe to a Pandas dataframe. This will have the effect of pulling the data into memory on the driver node. NOTE: This will be problematic for very large datasets, not an issue for this tiny dataset.

In [19]:
df_pandas = df.toPandas()

### 5) Display your new Pandas dataframe in the next cell.

NOTE: Although some Databricks specific commands like "display", which are not part of open source Spark, will work with your new Pandas dataframe, it is not required for this example. Unlike Pyspark, Python/Pandas is not lazily executed, so some paradigms are different.

In [21]:
# TODO
df_pandas

,_c0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

### 6) Filter the Pandas dataframe so it only shows rows with MPG greater than 20 and display it.

In [23]:
# TODO
df_pandas[df_pandas["mpg"]>=20]

,_c0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

### 7) Use Pandas to count how many rows have MPG greater than 20.

In [25]:
# TODO
df_pandas[df_pandas["mpg"]>=20]['mpg'].count()

### 8) What is the average MPG for the 4 cylinder, 6 cylinder, and 8 cylinder cars?

In [27]:
# TODO
df_pandas[df_pandas["mpg"]>=20]['mpg'].count()

## That's it!

You can download a copy of the this notebook and push it to your Homegrown repo. Theres a dropdown menu up above that has "export" as an option. Do that and choose iPython notebook.